server:
  port: 3030

# 로깅 설정
logger:
  - log
  - debug
  - error
  - warn

db:
  # 공지사항 데이터베이스
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  database: database_development
  synchronize: true
  # (Change me)
  # 데이터베이스 서버의 타임존
  timezone: '+09:00'
